### ISSUE TITLE
Usage with Capistrando and capistrano/rbenv plugin

### ISSUE THREAD

**Issue by guillehorno** [fullstaq-labs/fullstaq-ruby-server-edition#46]
Hi, 

I just installed fullstaq-ruby on a new server. Everything worked out fine. I followed the instructions regarding the rbenv integrations, got it working ok. When I write `rbenv versions` the output shows me the correct fullstaq-ruby installed version:
```
$ rbenv versions
* 2.7.1-jemalloc (set by /home/emeral/.rbenv/version
```
I added the line indicating the version in the deploy.rb file:
```
# config/deploy.rb
set :rbenv_ruby, '2.7.1-jemalloc'
```
When I try to run `cap deploy` it looks like it still tries to check if the ruby version is installed on the `.rbenv`home folder:
```
00:00 rbenv:validate
      WARN  rbenv: 2.7.1-jemalloc is not installed or not found in /usr/local/rbenv/versions/2.7.1-jemalloc
````
I've tried setting the rbenv_custom_path to the fullstaq folder
```
set :rbenv_custom_path, '/usr/lib/fullstaq-ruby/'
``` 
It works initially (it fools this initial check) but then it fails when capistrano tries to use that path to execute rbenv 
```
/usr/lib/fullstaq-ruby//bin/rbenv
```

Is there something else I'm missing? Thanks!!

**Comment by FooBarWidget** [comment]
Fullstaq Ruby uses a [modified rbenv](https://github.com/fullstaq-labs/fullstaq-rbenv) which adds [support for system-wide installed Rubies](https://github.com/fullstaq-labs/fullstaq-rbenv/blob/master/README.md#system-wide-ruby-installations). It looks like capistrano-rbenv is written with the assumption that Rubies are always located in RBENV_DIR/versions, which is not the case in fullstaq-rbenv. You should submit a feature request to capistrano-rbenv.

**Comment by guillehorno** [comment]
Ok. I'll explore a solution with the `capistrano/rbenv` plugin and collaborate with a PR if there's something to add to the documentation here, thanks!!

**Comment by guillehorno** [comment]
Hi, I think I've found a way to do it. There's a "hidden" option (at least it was not documented) to set the rbenv_ruby_dir in the `capistrano/rbenv` plugin.

That, combined with altering a little bit the rbenv_prefix option, so it point to the correct rbenv bin, works ok.  I've already submitted a PR on the `capistrano/rbenv` plugin to have that option documented (https://github.com/capistrano/rbenv/pull/91).

I've just sumitted a PR to document the neccesary options to add for the `capistrano/rbenv` plugins https://github.com/fullstaq-labs/fullstaq-ruby-server-edition/pull/47

Thanks :)

**Comment by FooBarWidget** [comment]
Thanks for the pull request @guillehorno, and thanks for figuring out this issue!

I've also done some investigations, and I think the issue can be solved in a better way. Instead of setting `rbenv_ruby_dir`, we could set:

~~~
set :rbenv_custom_path, '/usr/lib/rbenv'
~~~

This is the path to fullstaq-rbenv's system-wide installation directory. /usr/lib/rbenv/versions/* are symlinks to /usr/lib/fullstaq-ruby/versions/*. This will, capistrano-rbenv will end up checking whether `/usr/lib/rbenv/versions/#{rbenv_ruby}` exists.

However, this requires a change on the Fullstaq Ruby side. With the above option, we capistrano-rbenv will end up mapping 'ruby' to `/usr/lib/rbenv/bin/rbenv exec ruby`. However, `/usr/lib/rbenv/bin/rbenv` does not exist: we don't package it. So we need to modify the fullstaq-rbenv packaging script (container-entrypoints/build-rbenv-{deb,rpm}) to package /usr/lib/rbenv/bin.

We could make things *even better* if we modify capistrano-rbenv as well. Imagine that, instead of setting `rbenv_custom_path`, we could set:

~~~
set :rbenv_type, :fullstaq
~~~

This would make capistrano-rbenv autodetect that `rbenv_path` should be /usr/lib/rbenv.

Would you like to give making these changes a try? If not, let me know, and I'll do it instead.

If you do choose to contribute these changes, please don't forget to add a test case as well.

**Comment by FooBarWidget** [comment]
Thanks @guillehorno! I've posted some feedback in the PR.

**Comment by FooBarWidget** [comment]
This has been implemented.
