### ISSUE TITLE
Ruby header files missing?

### ISSUE THREAD

**Issue by arashster** [fullstaq-labs/fullstaq-ruby-server-edition#80]
**Describe the bug**

Currently using ubuntu 20.04 64-bit, for some reason, when using fullstaq ruby (tried v 2.6 and 2.7), I am unable to compile `racc` when bundling my application.

I've installed build-essential and ruby-dev packages on the machine.

Similarly, trying to do a 

`gem install bcrypt
`
fails as well.

The install/bundle works fine when using the system ruby (ruby2.7) that comes with Ubuntu.

Not sure what would be the cause of this failure.

Is fullstaq-ruby unable to find the Ruby header files?

**Comment by FooBarWidget** [comment]
When using Fullstaq Ruby, you don't need ruby-dev, because ruby-dev belongs to the distribution-managed Ruby version. The Fullstaq Ruby packages already contain headers.

Installing bcrypt indeed fails for me as well. But it's not because of missing Ruby headers, but because it tries to look for 'mkdir' in the wrong directory:

~~~
make: /usr/bin/mkdir: Command not found
~~~

This in turn happens because when Ruby was compiled, it somehow detected that mkdir was in /usr/bin (instead of /bin):

~~~ruby
>> require 'rbconfig'
>> pp RbConfig::CONFIG['MAKEDIRS']
"/usr/bin/mkdir -p"
~~~

And that in turn happens because the Fullstaq Ruby packages for Ubuntu 20.04 were built inside a Docker container. In the Docker image for Ubuntu 20.04, mkdir is in both /usr/bin and /bin:

~~~
$ docker run -ti --rm ubuntu:20.04 ls /usr/bin/mkdir
/usr/bin/mkdir
$ docker run -ti --rm ubuntu:20.04 ls /bin/mkdir
/bin/mkdir
~~~

Yet on an Ubuntu 20.04 VM, it is not:

~~~
$ ls /usr/bin/mkdir
ls: cannot access '/usr/bin/mkdir': No such file or directory
$ ls /bin/mkdir
/bin/mkdir
~~~

🤔

**Comment by FooBarWidget** [comment]
Upon further investigation, it seems that the rogue /usr/bin/mkdir *only* appears in the Ubuntu 20.04 Docker image. It doesn't appear in the Ubuntu 18.04 image, nor in the Debian 10 image.

I'll have it removed from our build images, which should fix this problem.

**Comment by arashster** [comment]
If it's of any help, I'm running into this issue on a Ubuntu 20.04 VPS that is using OpenVZ.

**Comment by FooBarWidget** [comment]
Fixed. Updates will be published when the CI finishes.

**Comment by FooBarWidget** [comment]
It seems my initial analysis of this problem was wrong, and the fix never worked in the first place. See #101 for a follow-up.
